spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simplest
    username: postgres
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
mybatis:
  type-aliases-package: com.fengyiai.simpledu.model
  mapper-locations: classpath*:com/fengyiai/simpledu/mapper/impl/*.xml
server:
  port: 8000